// Generated by @kubuno/views-compiler from src/core/admin/AuthMethodsPanel.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, Switch as __Switch, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/AuthMethodsPanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/AuthMethodsPanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 34). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Switch.OnCheckedChanged` (line 56). */
  abstract switch_checked_changed(sender: __Switch, e: __ValueChangedEventArgs): void | Promise<void>
}
