// Generated by @kubuno/views-compiler from src/core/admin/ModuleAdminSettings.kbview — do not edit (rebuilt on every change; never committed).
import type { Callout as __Callout, EventArgs as __EventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ModuleAdminSettingsProps as __Props } from './ModuleAdminSettings'

/** The render plan of `src/core/admin/ModuleAdminSettings.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/ModuleAdminSettings.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Callout.OnDismiss` (line 30). */
  abstract callout_dismiss(sender: __Callout, e: __EventArgs): void | Promise<void>
}
