// Generated by @kubuno/views-compiler from src/core/admin/OrgUnitPicker.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { OrgUnitPickerProps as __Props } from './OrgUnitPicker'

/** The render plan of `src/core/admin/OrgUnitPicker.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/OrgUnitPicker.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `FloatingWindow.OnClose` (line 11). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 10). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 20). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseDown` (line 2). */
  abstract panel_mouse_down(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
