// Generated by @kubuno/views-compiler from src/core/admin/OrgUnitScopePanel.kbview — do not edit (rebuilt on every change; never committed).
import type { LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, Panel as __Panel, RadioButton as __RadioButton, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './OrgUnitScopePanel'

/** The render plan of `src/core/admin/OrgUnitScopePanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/OrgUnitScopePanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `LinkLabel.OnClick` (line 71). */
  abstract link_label_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 12). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 28). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 48). */
  abstract panel_click3(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 36). */
  abstract radio_button_checked_changed(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 40). */
  abstract radio_button_checked_changed2(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
}
