// Generated by @kubuno/views-compiler from src/core/admin/sections/user-detail/UserDetailSection.kbview — do not edit (rebuilt on every change; never committed).
import type { EmptyState as __EmptyState, EventArgs as __EventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { UserDetailSectionProps as __Props } from './UserDetailSection'

/** The render plan of `src/core/admin/sections/user-detail/UserDetailSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/user-detail/UserDetailSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `EmptyState.OnAction` (line 15). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
  /** Handles `EmptyState.OnSecondaryAction` (line 16). */
  abstract empty_state_secondary_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
