// Generated by @kubuno/views-compiler from src/core/admin/health/HealthSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EmptyState as __EmptyState, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/health/HealthSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/health/HealthSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `EmptyState.OnAction` (line 13). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 29). */
  abstract onRefreshAll(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
