// Generated by @kubuno/views-compiler from src/core/pages/HomePage.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/pages/HomePage.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/pages/HomePage.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 48). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 55). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `LinkLabel.OnClick` (line 16). */
  abstract link_label_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 38). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
