// Generated by @kubuno/views-compiler from src/core/admin/theme/groups/data/CalloutsAndProgress.kbview — do not edit (rebuilt on every change; never committed).
import type { Callout as __Callout, EventArgs as __EventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/theme/groups/data/CalloutsAndProgress.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/theme/groups/data/CalloutsAndProgress.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Callout.OnAction` (line 10). */
  abstract callout_action(sender: __Callout, e: __EventArgs): void | Promise<void>
  /** Handles `Callout.OnAction` (line 17). */
  abstract callout_action2(sender: __Callout, e: __EventArgs): void | Promise<void>
}
