// Generated by @kubuno/views-compiler from src/core/admin/sections/holidays/CalendarDetail.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, NumericField as __NumericField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { CalendarDetailProps as __Props } from './CalendarDetail'

/** The render plan of `src/core/admin/sections/holidays/CalendarDetail.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/holidays/CalendarDetail.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 7). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `NumericField.OnValueChanged` (line 33). */
  abstract numeric_field_value_changed(sender: __NumericField, e: __ValueChangedEventArgs): void | Promise<void>
}
