// Generated by @kubuno/views-compiler from src/core/admin/sections/holidays/HolidayDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, NumericField as __NumericField, Panel as __Panel, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { HolidayDialogProps as __Props } from './HolidayDialog'

/** The render plan of `src/core/admin/sections/holidays/HolidayDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/holidays/HolidayDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `FloatingWindow.OnClose` (line 12). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 11). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `NumericField.OnValueChanged` (line 41). */
  abstract numeric_field_value_changed(sender: __NumericField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `NumericField.OnValueChanged` (line 49). */
  abstract numeric_field_value_changed2(sender: __NumericField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseDown` (line 2). */
  abstract panel_mouse_down(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
