// Generated by @kubuno/views-compiler from src/core/admin/sections/data-export/ExportSubjectsCard.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EmptyState as __EmptyState, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ExportSubjectsCardProps as __Props } from './ExportSubjectsCard'

/** The render plan of `src/core/admin/sections/data-export/ExportSubjectsCard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/data-export/ExportSubjectsCard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 4). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `EmptyState.OnAction` (line 17). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
