//! Loading the shipped referential.
//!
//! ## The invariant this file exists to hold
//!
//! **An upgrade never undoes an edit.** Somebody corrected a date, disabled a
//! day their organisation does not take, or renamed one in their own words;
//! shipping a newer dataset must leave all three alone. Three columns carry
//! that promise:
//!
//! * `is_overridden` — set the first time the console writes a row. The upsert
//!   below skips those rows entirely.
//! * `enabled` — never written by the seeder, in either direction.
//! * `is_orphan` — a row the new dataset no longer knows, but which somebody
//!   edited. Deleting it would throw the edit away; keeping it quietly would go
//!   on announcing a day the source dropped. It is kept and flagged, and the
//!   console shows it as what it is.
//!
//! Untouched rows are re-matched on `(calendar, key)` and rewritten, which is
//! what makes a corrected upstream date actually arrive.
//!
//! ## Why the whole thing is skipped most of the time
//!
//! The dataset carries a version. It is written into `intl.holidays_dataset`
//! after a successful load and compared on the next boot; when they match,
//! nothing is parsed at all. The embedded JSON is two megabytes, and paying for
//! it at every restart to discover that nothing changed is the kind of cost that
//! turns into "the server takes a while to come up".

use std::collections::HashMap;

use serde::Deserialize;
use serde_json::{json, Value};
use sqlx::PgPool;
use uuid::Uuid;

use super::model::Rule;
use crate::errors::AppError;

/// Generated by `_tools/gen_holidays.py`. Embedded rather than read from disk:
/// a packaging mistake that leaves the file behind would otherwise turn into an
/// instance that starts fine and knows no holidays.
const DATASET: &str = include_str!("../../data/holidays.json");

/// The setting that records what is currently loaded.
const VERSION_KEY: &str = "intl.holidays_dataset";

#[derive(Debug, Deserialize)]
struct Dataset {
    version: String,
    year_range: [i32; 2],
    countries: Vec<CountryEntry>,
}

#[derive(Debug, Deserialize)]
struct CountryEntry {
    code: String,
    #[serde(default)]
    names: HashMap<String, String>,
    calendars: Vec<CalendarEntry>,
}

#[derive(Debug, Deserialize)]
struct CalendarEntry {
    code: String,
    #[serde(default)]
    subdivision: Option<String>,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    holidays: Vec<HolidayEntry>,
    /// Keys of the country's days this subdivision does not observe.
    #[serde(default)]
    excluded: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct HolidayEntry {
    key: String,
    name: String,
    #[serde(default)]
    names: HashMap<String, String>,
    category: String,
    kind: String,
    rule: Value,
    #[serde(default)]
    observance: Option<String>,
    #[serde(default)]
    from_year: Option<i32>,
    #[serde(default)]
    to_year: Option<i32>,
}

/// What a load did, for the startup log and the console's "reload" button.
#[derive(Debug, Default, Clone, serde::Serialize)]
pub struct SeedReport {
    pub version: String,
    pub calendars: usize,
    pub holidays: usize,
    pub skipped_overridden: usize,
    pub orphaned: usize,
    pub removed: usize,
    /// True when the dataset was already loaded and nothing was parsed.
    pub up_to_date: bool,
}

/// Loads the shipped dataset unless it is already in place.
///
/// Never fatal: an instance that fails to seed still serves whatever it already
/// has, and every path that reads holidays tolerates an empty referential.
pub async fn ensure_dataset(db: &PgPool) -> SeedReport {
    match load(db, false).await {
        Ok(report) => {
            if report.up_to_date {
                tracing::debug!(version = %report.version, "holidays: référentiel déjà à jour");
            } else {
                tracing::info!(
                    version = %report.version,
                    calendars = report.calendars,
                    holidays = report.holidays,
                    preserved = report.skipped_overridden,
                    orphaned = report.orphaned,
                    removed = report.removed,
                    "holidays: référentiel chargé"
                );
            }
            report
        }
        Err(e) => {
            tracing::error!(error = %e, "holidays: chargement du référentiel impossible");
            SeedReport::default()
        }
    }
}

/// The version the binary carries, without parsing the whole file.
///
/// The generator writes `version` first, so the answer is a few dozen bytes in.
/// Worth the small parse: it is what makes the common boot free.
pub fn shipped_version() -> String {
    #[derive(Deserialize)]
    struct JustVersion {
        version: String,
    }
    serde_json::from_str::<JustVersion>(DATASET)
        .map(|v| v.version)
        .unwrap_or_else(|_| "inconnue".into())
}

/// One shipped day, as the dataset declares it.
#[derive(Debug, Clone)]
pub struct ShippedHoliday {
    pub name: String,
    pub names: Value,
    pub category: String,
    pub kind: String,
    pub rule: Value,
    pub observance: String,
    pub from_year: Option<i32>,
    pub to_year: Option<i32>,
}

/// Looks one day up in the shipped dataset — what "rétablir la version
/// d'origine" restores.
///
/// Parses on demand rather than keeping the dataset in memory: this is a button
/// somebody presses a few times a year, and holding twenty megabytes of parsed
/// JSON for its convenience would be a permanent cost for a rare answer.
pub fn shipped_holiday(calendar_code: &str, key: &str) -> Option<ShippedHoliday> {
    let dataset: Dataset = serde_json::from_str(DATASET)
        .map_err(|e| tracing::error!(error = %e, "holidays: jeu de données livré illisible"))
        .ok()?;

    let entry = dataset
        .countries
        .iter()
        .flat_map(|country| country.calendars.iter())
        .find(|calendar| calendar.code.eq_ignore_ascii_case(calendar_code))?
        .holidays
        .iter()
        .find(|holiday| holiday.key == key)?;

    Some(ShippedHoliday {
        name: entry.name.clone(),
        names: json!(entry.names),
        category: entry.category.clone(),
        kind: entry.kind.clone(),
        rule: entry.rule.clone(),
        observance: entry.observance.clone().unwrap_or_else(|| "none".into()),
        from_year: entry.from_year,
        to_year: entry.to_year,
    })
}

/// Loads the dataset. `force` re-applies it even when the version matches —
/// what the console's "recharger le référentiel" does after somebody has
/// deleted rows they now want back.
pub async fn load(db: &PgPool, force: bool) -> Result<SeedReport, AppError> {
    let current: Option<String> = sqlx::query_scalar(
        "SELECT value #>> '{}' FROM core.settings WHERE key = $1",
    )
    .bind(VERSION_KEY)
    .fetch_optional(db)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "holidays: lecture de la version chargée");
        AppError::Database(e)
    })?
    .flatten();

    let shipped = shipped_version();
    if !force && current.as_deref() == Some(shipped.as_str()) {
        return Ok(SeedReport {
            version: shipped,
            up_to_date: true,
            ..SeedReport::default()
        });
    }

    let dataset: Dataset = serde_json::from_str(DATASET).map_err(|e| {
        tracing::error!(error = %e, "holidays: jeu de données livré illisible");
        AppError::Internal(anyhow::anyhow!("Jeu de données des jours fériés illisible"))
    })?;

    let mut report = SeedReport {
        version: dataset.version.clone(),
        ..SeedReport::default()
    };

    let mut tx = db.begin().await.map_err(|e| {
        tracing::error!(error = %e, "holidays: ouverture de la transaction de chargement");
        AppError::Database(e)
    })?;

    // Every (calendar code, holiday key) the dataset declares — what the
    // removal pass at the end compares against.
    let mut shipped_keys: Vec<(String, String)> = Vec::new();

    for country in &dataset.countries {
        let country_name = country
            .names
            .get("en")
            .cloned()
            .unwrap_or_else(|| country.code.clone());

        let mut parent_id: Option<Uuid> = None;
        for entry in &country.calendars {
            let is_country = entry.subdivision.is_none();
            let name = match (&entry.name, is_country) {
                (Some(name), _) => name.clone(),
                (None, true) => country_name.clone(),
                (None, false) => entry.code.clone(),
            };
            let names = if is_country {
                json!(country.names)
            } else {
                json!({})
            };
            // A calendar carries a coverage window only when something in it
            // actually runs out — the explicit date lists. A country whose days
            // are all rules answers for every year, and saying otherwise would
            // put a false limit in front of the reader.
            let bounded = entry.holidays.iter().any(|h| h.kind == "dates");
            let (coverage_from, coverage_to) = if bounded {
                (Some(dataset.year_range[0]), Some(dataset.year_range[1]))
            } else {
                (None, None)
            };

            let calendar_id: Uuid = sqlx::query_scalar(
                r#"
                INSERT INTO core.holiday_calendars
                    (code, country_code, subdivision, parent_id, name, names,
                     is_builtin, coverage_from, coverage_to)
                VALUES ($1, $2, $3, $4, $5, $6, TRUE, $7, $8)
                ON CONFLICT (code) DO UPDATE SET
                    country_code  = EXCLUDED.country_code,
                    subdivision   = EXCLUDED.subdivision,
                    parent_id     = EXCLUDED.parent_id,
                    -- An administrator's wording survives; everything else is
                    -- refreshed. `enabled` is absent on purpose.
                    name          = CASE WHEN core.holiday_calendars.is_overridden
                                         THEN core.holiday_calendars.name ELSE EXCLUDED.name END,
                    names         = CASE WHEN core.holiday_calendars.is_overridden
                                         THEN core.holiday_calendars.names ELSE EXCLUDED.names END,
                    is_builtin    = TRUE,
                    coverage_from = EXCLUDED.coverage_from,
                    coverage_to   = EXCLUDED.coverage_to
                RETURNING id
                "#,
            )
            .bind(&entry.code)
            .bind(&country.code)
            .bind(entry.subdivision.as_deref())
            .bind(parent_id)
            .bind(&name)
            .bind(&names)
            .bind(coverage_from)
            .bind(coverage_to)
            .fetch_one(&mut *tx)
            .await
            .map_err(|e| {
                tracing::error!(error = %e, code = %entry.code, "holidays: écriture d'un calendrier");
                AppError::Database(e)
            })?;

            if is_country {
                parent_id = Some(calendar_id);
            }
            report.calendars += 1;

            for holiday in &entry.holidays {
                // Refused here rather than at read time: a rule the expander
                // cannot answer for must never reach the table, or it becomes a
                // row the console shows and nothing ever produces a date for.
                if let Err(e) = Rule::from_parts(&holiday.kind, &holiday.rule) {
                    tracing::warn!(
                        calendar = %entry.code, key = %holiday.key, error = %e,
                        "holidays: règle livrée invalide, ignorée"
                    );
                    continue;
                }
                shipped_keys.push((entry.code.clone(), holiday.key.clone()));

                let written = sqlx::query(
                    r#"
                    INSERT INTO core.holidays
                        (calendar_id, key, name, names, category, kind, rule, observance,
                         from_year, to_year, is_builtin)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, TRUE)
                    ON CONFLICT (calendar_id, key) DO UPDATE SET
                        name       = EXCLUDED.name,
                        names      = EXCLUDED.names,
                        category   = EXCLUDED.category,
                        kind       = EXCLUDED.kind,
                        rule       = EXCLUDED.rule,
                        observance = EXCLUDED.observance,
                        from_year  = EXCLUDED.from_year,
                        to_year    = EXCLUDED.to_year,
                        is_builtin = TRUE,
                        -- Back from the dead: a row that was orphaned by a
                        -- previous dataset and returns in this one is no longer
                        -- one.
                        is_orphan  = FALSE
                    -- The whole promise of this file, in one clause.
                    WHERE core.holidays.is_overridden IS NOT TRUE
                    "#,
                )
                .bind(calendar_id)
                .bind(&holiday.key)
                .bind(&holiday.name)
                .bind(json!(holiday.names))
                .bind(&holiday.category)
                .bind(&holiday.kind)
                .bind(&holiday.rule)
                .bind(holiday.observance.as_deref().unwrap_or("none"))
                .bind(holiday.from_year)
                .bind(holiday.to_year)
                .execute(&mut *tx)
                .await
                .map_err(|e| {
                    tracing::error!(error = %e, calendar = %entry.code, key = %holiday.key,
                                    "holidays: écriture d'une journée");
                    AppError::Database(e)
                })?;

                if written.rows_affected() == 0 {
                    report.skipped_overridden += 1;
                } else {
                    report.holidays += 1;
                }
            }

            // Exclusions are replaced wholesale: they are three rows at most per
            // calendar, and a diff would cost more than the rewrite.
            sqlx::query("DELETE FROM core.holiday_exclusions WHERE calendar_id = $1")
                .bind(calendar_id)
                .execute(&mut *tx)
                .await
                .map_err(|e| {
                    tracing::error!(error = %e, "holidays: purge des exclusions");
                    AppError::Database(e)
                })?;
            for key in &entry.excluded {
                sqlx::query(
                    "INSERT INTO core.holiday_exclusions (calendar_id, key) VALUES ($1, $2) \
                     ON CONFLICT DO NOTHING",
                )
                .bind(calendar_id)
                .bind(key)
                .execute(&mut *tx)
                .await
                .map_err(|e| {
                    tracing::error!(error = %e, "holidays: écriture d'une exclusion");
                    AppError::Database(e)
                })?;
            }
        }
    }

    // ── What the new dataset no longer knows ────────────────────────────────
    //
    // Two fates, and the difference is whether somebody put work into the row.
    let (codes, keys): (Vec<String>, Vec<String>) = shipped_keys.into_iter().unzip();

    let removed = sqlx::query(
        r#"
        DELETE FROM core.holidays h
         USING core.holiday_calendars c
         WHERE c.id = h.calendar_id
           AND h.is_builtin
           AND h.is_overridden IS NOT TRUE
           AND NOT EXISTS (
               SELECT 1 FROM UNNEST($1::text[], $2::text[]) AS s(code, key)
                WHERE s.code = c.code AND s.key = h.key)
        "#,
    )
    .bind(&codes)
    .bind(&keys)
    .execute(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "holidays: retrait des journées disparues du jeu de données");
        AppError::Database(e)
    })?;
    report.removed = removed.rows_affected() as usize;

    let orphaned = sqlx::query(
        r#"
        UPDATE core.holidays h
           SET is_orphan = TRUE
          FROM core.holiday_calendars c
         WHERE c.id = h.calendar_id
           AND h.is_builtin
           AND h.is_overridden
           AND NOT EXISTS (
               SELECT 1 FROM UNNEST($1::text[], $2::text[]) AS s(code, key)
                WHERE s.code = c.code AND s.key = h.key)
           AND h.is_orphan IS NOT TRUE
        "#,
    )
    .bind(&codes)
    .bind(&keys)
    .execute(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "holidays: marquage des journées orphelines");
        AppError::Database(e)
    })?;
    report.orphaned = orphaned.rows_affected() as usize;

    // The reverse move: an edited row the dataset dropped once and now ships
    // again. The upsert above cannot clear the flag on it — it skips overridden
    // rows by design — so it is cleared here, where the comparison is made.
    sqlx::query(
        r#"
        UPDATE core.holidays h
           SET is_orphan = FALSE
          FROM core.holiday_calendars c
         WHERE c.id = h.calendar_id
           AND h.is_orphan
           AND EXISTS (
               SELECT 1 FROM UNNEST($1::text[], $2::text[]) AS s(code, key)
                WHERE s.code = c.code AND s.key = h.key)
        "#,
    )
    .bind(&codes)
    .bind(&keys)
    .execute(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "holidays: levée du marquage orphelin");
        AppError::Database(e)
    })?;

    sqlx::query(
        "UPDATE core.settings SET value = to_jsonb($1::text), updated_at = NOW() WHERE key = $2",
    )
    .bind(&dataset.version)
    .bind(VERSION_KEY)
    .execute(&mut *tx)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "holidays: enregistrement de la version chargée");
        AppError::Database(e)
    })?;

    tx.commit().await.map_err(|e| {
        tracing::error!(error = %e, "holidays: validation du chargement");
        AppError::Database(e)
    })?;

    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The dataset is embedded in the binary, so a corrupt one is a build-time
    /// problem — and this is the test that turns it into one.
    #[test]
    fn the_shipped_dataset_parses_and_covers_the_world() {
        let dataset: Dataset = serde_json::from_str(DATASET).expect("jeu de données lisible");
        assert!(
            dataset.countries.len() > 150,
            "seulement {} pays livrés",
            dataset.countries.len()
        );
        assert!(dataset.year_range[1] > dataset.year_range[0]);
        assert!(!dataset.version.is_empty());

        let france = dataset
            .countries
            .iter()
            .find(|c| c.code == "FR")
            .expect("la France est livrée");
        let national = &france.calendars[0];
        assert_eq!(national.holidays.len(), 11, "onze jours fériés français");
        assert!(france.calendars.len() > 1, "les subdivisions sont livrées");
    }

    /// Every shipped rule must be one the expander can answer for; a kind it
    /// does not know would be dropped at load time with a warning nobody reads.
    #[test]
    fn every_shipped_rule_is_expandable() {
        let dataset: Dataset = serde_json::from_str(DATASET).expect("jeu de données lisible");
        let mut checked = 0usize;
        for country in &dataset.countries {
            for calendar in &country.calendars {
                for holiday in &calendar.holidays {
                    Rule::from_parts(&holiday.kind, &holiday.rule).unwrap_or_else(|e| {
                        panic!("{}/{} : {e}", calendar.code, holiday.key)
                    });
                    super::super::model::Category::parse(&holiday.category)
                        .unwrap_or_else(|e| panic!("{}/{} : {e}", calendar.code, holiday.key));
                    super::super::model::Observance::parse(
                        holiday.observance.as_deref().unwrap_or("none"),
                    )
                    .unwrap_or_else(|e| panic!("{}/{} : {e}", calendar.code, holiday.key));
                    checked += 1;
                }
            }
        }
        assert!(checked > 3000, "seulement {checked} règles vérifiées");
    }
}
