// Generated by @kubuno/views-compiler from src/core/admin/detectors/DetectorEditor.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, ComboBox as __ComboBox, MouseEventArgs as __MouseEventArgs, Switch as __Switch, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './DetectorEditor'

/** The render plan of `src/core/admin/detectors/DetectorEditor.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/detectors/DetectorEditor.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 4). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 178). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 179). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `ComboBox.OnSelectedValueChanged` (line 60). */
  abstract combo_box_selected_value_changed(sender: __ComboBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `ComboBox.OnSelectedValueChanged` (line 86). */
  abstract combo_box_selected_value_changed2(sender: __ComboBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `ComboBox.OnSelectedValueChanged` (line 123). */
  abstract combo_box_selected_value_changed3(sender: __ComboBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Switch.OnCheckedChanged` (line 68). */
  abstract switch_checked_changed(sender: __Switch, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Switch.OnCheckedChanged` (line 148). */
  abstract switch_checked_changed2(sender: __Switch, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 34). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 39). */
  abstract text_field_text_changed2(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 45). */
  abstract text_field_text_changed3(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
