// Generated by @kubuno/views-compiler from src/core/admin/panels/PanelCard.kbview — do not edit (rebuilt on every change; never committed).
import type { MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './PanelCard'

/** The render plan of `src/core/admin/panels/PanelCard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/panels/PanelCard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnClick` (line 84). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
