// Generated by @kubuno/views-compiler from src/core/admin/roles/AssignRoleDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, Panel as __Panel, RadioButton as __RadioButton, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AssignRoleDialogProps as __Props } from './AssignRoleDialog'

/** The render plan of `src/core/admin/roles/AssignRoleDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/roles/AssignRoleDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `FloatingWindow.OnClose` (line 12). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 11). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 35). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 47). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 96). */
  abstract panel_click3(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 14). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 65). */
  abstract radio_button_checked_changed(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 82). */
  abstract radio_button_checked_changed2(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
}
