// Generated by @kubuno/views-compiler from src/core/admin/roles/RoleCreateDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { RoleCreateDialogProps as __Props } from './RoleCreateDialog'

/** The render plan of `src/core/admin/roles/RoleCreateDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/roles/RoleCreateDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `FloatingWindow.OnClose` (line 12). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 11). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 13). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 22). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
