// Generated by @kubuno/views-compiler from src/core/admin/sections/directory-settings/CheckboxRow.kbview — do not edit (rebuilt on every change; never committed).
import type { CheckBox as __CheckBox, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { CheckboxRowProps as __Props } from './CheckboxRow'

/** The render plan of `src/core/admin/sections/directory-settings/CheckboxRow.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/directory-settings/CheckboxRow.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `CheckBox.OnCheckedChanged` (line 8). */
  abstract check_box_checked_changed(sender: __CheckBox, e: __ValueChangedEventArgs): void | Promise<void>
}
