// Generated by @kubuno/views-compiler from src/core/admin/sections/directory-settings/DirectorySettingsSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Callout as __Callout, EmptyState as __EmptyState, EventArgs as __EventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/sections/directory-settings/DirectorySettingsSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/directory-settings/DirectorySettingsSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Callout.OnDismiss` (line 21). */
  abstract callout_dismiss(sender: __Callout, e: __EventArgs): void | Promise<void>
  /** Handles `EmptyState.OnAction` (line 30). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
