// Generated by @kubuno/views-compiler from src/core/admin/sections/directory-settings/ToggleRow.kbview — do not edit (rebuilt on every change; never committed).
import type { Switch as __Switch, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { RowProps as __Props } from './ToggleRow'

/** The render plan of `src/core/admin/sections/directory-settings/ToggleRow.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/directory-settings/ToggleRow.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Switch.OnCheckedChanged` (line 7). */
  abstract switch_checked_changed(sender: __Switch, e: __ValueChangedEventArgs): void | Promise<void>
}
