// Generated by @kubuno/views-compiler from src/core/admin/backup/BackupPanel.kbview — do not edit (rebuilt on every change; never committed).
import type { EmptyState as __EmptyState, EventArgs as __EventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/backup/BackupPanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/backup/BackupPanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `EmptyState.OnAction` (line 13). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
