// Generated by @kubuno/views-compiler from src/core/admin/sections/AuditSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AdminSectionProps as __Props } from './AuditSection'

/** The render plan of `src/core/admin/sections/AuditSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/AuditSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 45). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 36). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 12). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
}
