// Generated by @kubuno/views-compiler from src/core/admin/rules/ModePicker.kbview — do not edit (rebuilt on every change; never committed).
import type { RadioButton as __RadioButton, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './ModePicker'

/** The render plan of `src/core/admin/rules/ModePicker.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/rules/ModePicker.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `RadioButton.OnCheckedChanged` (line 8). */
  abstract radio_button_checked_changed(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
}
