// Generated by @kubuno/views-compiler from src/core/admin/reports/paged/PagedPreview.kbview — do not edit (rebuilt on every change; never committed).
import type { MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { PagedPreviewProps as __Props } from './PagedPreview'

/** The render plan of `src/core/admin/reports/paged/PagedPreview.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/reports/paged/PagedPreview.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnClick` (line 31). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 40). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 47). */
  abstract panel_click3(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 55). */
  abstract panel_click4(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
