// Generated by @kubuno/views-compiler from src/core/admin/sections/resources/OverviewTab.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, Callout as __Callout, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { OverviewTabProps as __Props } from './OverviewTab'

/** The render plan of `src/core/admin/sections/resources/OverviewTab.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/resources/OverviewTab.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 39). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Callout.OnAction` (line 10). */
  abstract callout_action(sender: __Callout, e: __EventArgs): void | Promise<void>
}
