// Generated by @kubuno/views-compiler from src/core/admin/sections/data-migration/CampaignWizard.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, ComboBox as __ComboBox, EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { CampaignWizardProps as __Props } from './CampaignWizard'

/** The render plan of `src/core/admin/sections/data-migration/CampaignWizard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/data-migration/CampaignWizard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 84). */
  abstract applyBulk(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 186). */
  abstract back(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 85). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 150). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `ComboBox.OnSelectedValueChanged` (line 62). */
  abstract combo_box_selected_value_changed(sender: __ComboBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `ComboBox.OnSelectedValueChanged` (line 113). */
  abstract combo_box_selected_value_changed2(sender: __ComboBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnClose` (line 12). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 11). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 123). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 158). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseDown` (line 2). */
  abstract panel_mouse_down(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 98). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 104). */
  abstract text_field_text_changed2(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
