// Generated by @kubuno/views-compiler from src/core/shell/menus/AccountMenu.kbcontrol — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, IconButton as __IconButton, LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, ScrollArea as __ScrollArea, Stack as __Stack, UserControl as __UserControl, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AccountMenuProps as __Props } from './AccountMenu'

/** The render plan of `src/core/shell/menus/AccountMenu.kbcontrol`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/shell/menus/AccountMenu.kbcontrol`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** `<Stack x:Name="head">` (line 11) */
  readonly head: __Stack
  /** `<IconButton x:Name="close_button">` (line 14) */
  readonly close_button: __IconButton
  /** `<ScrollArea x:Name="body">` (line 17) */
  readonly body: __ScrollArea
  /** `<IconButton x:Name="camera_button">` (line 24) */
  readonly camera_button: __IconButton
  /** `<LinkLabel x:Name="manage">` (line 28) */
  readonly manage: __LinkLabel
  /** `<Stack x:Name="toggle">` (line 34) */
  readonly toggle: __Stack
  /** `<Stack x:Name="add_account">` (line 103) */
  readonly add_account: __Stack
  /** `<Stack x:Name="labels">` (line 108) */
  readonly labels: __Stack
  /** `<Stack x:Name="admin">` (line 113) */
  readonly admin: __Stack
  /** `<Stack x:Name="sign_out">` (line 118) */
  readonly sign_out: __Stack
  /** Handles `Stack.OnClick` (line 55). */
  abstract account_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
  /** Handles `UserControl.OnLoad` (line 10). */
  abstract account_menu_load(sender: __UserControl, e: __EventArgs): void | Promise<void>
  /** Handles `Stack.OnClick` (line 104). */
  abstract add_account_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Stack.OnClick` (line 114). */
  abstract admin_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
  /** Handles `IconButton.OnClick` (line 25). */
  abstract camera_button_click(sender: __IconButton, e: __MouseEventArgs): void | Promise<void>
  /** Handles `IconButton.OnClick` (line 14). */
  abstract close_button_click(sender: __IconButton, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Stack.OnClick` (line 109). */
  abstract labels_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
  /** Handles `LinkLabel.OnClick` (line 29). */
  abstract manage_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 92). */
  abstract open_remote_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 76). */
  abstract reconnect_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 77), `Button.OnClick` (line 93). */
  abstract remove_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Stack.OnClick` (line 119). */
  abstract sign_out_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Stack.OnClick` (line 35). */
  abstract toggle_click(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
}
