// Generated by @kubuno/views-compiler from src/core/auth/ForcePasswordChange.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/auth/ForcePasswordChange.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/auth/ForcePasswordChange.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 59). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 29). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 19). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 50). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
