// Generated by @kubuno/views-compiler from src/core/auth/LoginPage.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { LoginPageProps as __Props } from './LoginPage'

/** The render plan of `src/core/auth/LoginPage.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/auth/LoginPage.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnClick` (line 135). */
  abstract loadCaptcha(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 45). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 52). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 37). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 79). */
  abstract panel_submit2(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 115). */
  abstract panel_submit3(sender: __Panel, e: __EventArgs): void | Promise<void>
}
