// Generated by @kubuno/views-compiler from src/core/auth/ReauthDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './ReauthDialog'

/** The render plan of `src/core/auth/ReauthDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/auth/ReauthDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 21). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnClose` (line 8). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 9). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
}
