// Generated by @kubuno/views-compiler from src/core/auth/ResetPasswordPage.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/auth/ResetPasswordPage.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/auth/ResetPasswordPage.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `LinkLabel.OnClick` (line 72). */
  abstract link_label_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 14). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 25). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 44). */
  abstract panel_click3(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 36). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 65). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
