// Generated by @kubuno/views-compiler from src/core/admin/settings/InheritanceChainWindow.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { InheritanceChainWindowProps as __Props } from './InheritanceChainWindow'

/** The render plan of `src/core/admin/settings/InheritanceChainWindow.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/settings/InheritanceChainWindow.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `FloatingWindow.OnClose` (line 2). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
}
