// Generated by @kubuno/views-compiler from src/core/admin/settings/SettingsSaveBar.kbview — do not edit (rebuilt on every change; never committed).
import type { MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { SettingsSaveBarProps as __Props } from './SettingsSaveBar'

/** The render plan of `src/core/admin/settings/SettingsSaveBar.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/settings/SettingsSaveBar.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnClick` (line 12). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 19). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
