// Generated by @kubuno/views-compiler from src/core/auth/RegisterPage.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/auth/RegisterPage.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/auth/RegisterPage.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `LinkLabel.OnClick` (line 61). */
  abstract link_label_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 26). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 11). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
}
