// Generated by @kubuno/views-compiler from src/core/admin/sections/subscription/SupportCard.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { SupportCardProps as __Props } from './SupportCard'

/** The render plan of `src/core/admin/sections/subscription/SupportCard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/subscription/SupportCard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 15). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 31). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 32). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 41). */
  abstract button_click4(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
