// Generated by @kubuno/views-compiler from src/core/settings/sections/ClientsTab.kbview — do not edit (rebuilt on every change; never committed).
import type { LinkLabel as __LinkLabel, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/settings/sections/ClientsTab.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/ClientsTab.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Panel.OnClick` (line 69). */
  abstract copy(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `LinkLabel.OnClick` (line 29). */
  abstract link_label_click(sender: __LinkLabel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 45). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
