// Generated by @kubuno/views-compiler from src/core/settings/sections/CreateTokenForm.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { CreateTokenFormProps as __Props } from './CreateTokenForm'

/** The render plan of `src/core/settings/sections/CreateTokenForm.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/CreateTokenForm.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnSubmit` (line 3). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
}
