// Generated by @kubuno/views-compiler from src/core/settings/sections/NotificationsTab.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, Dropdown as __Dropdown, MouseEventArgs as __MouseEventArgs, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/settings/sections/NotificationsTab.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/NotificationsTab.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Dropdown.OnSelectedValueChanged` (line 13). */
  abstract dropdown_selected_value_changed(sender: __Dropdown, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Dropdown.OnSelectedValueChanged` (line 64). */
  abstract dropdown_selected_value_changed2(sender: __Dropdown, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 80). */
  abstract save(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
