// Generated by @kubuno/views-compiler from src/core/settings/sections/TwoFactorSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/settings/sections/TwoFactorSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/TwoFactorSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 37). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 49). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 77). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 38). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnSubmit` (line 71). */
  abstract panel_submit2(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 94). */
  abstract startSetup(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
