// Generated by @kubuno/views-compiler from src/core/admin/DonutChart.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { DonutChartProps as __Props } from './DonutChart'

/** The render plan of `src/core/admin/DonutChart.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/DonutChart.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnMouseEnter` (line 7). */
  abstract panel_mouse_enter(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseLeave` (line 7). */
  abstract panel_mouse_leave(sender: __Panel, e: __EventArgs): void | Promise<void>
}
