// Generated by @kubuno/views-compiler from src/core/admin/ModuleDatabaseCard.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, RadioButton as __RadioButton, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ModuleDatabaseCardProps as __Props } from './ModuleDatabaseCard'

/** The render plan of `src/core/admin/ModuleDatabaseCard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/ModuleDatabaseCard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 37). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 20). */
  abstract radio_button_checked_changed(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 25). */
  abstract radio_button_checked_changed2(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
}
