// Generated by @kubuno/views-compiler from src/core/admin/OAuthProvidersPanel.kbview — do not edit (rebuilt on every change; never committed).
import type { View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/OAuthProvidersPanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/OAuthProvidersPanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare class ViewBase extends __View<{}> {
}
