// Generated by @kubuno/views-compiler from src/core/admin/ResetPasswordDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, Panel as __Panel, RadioButton as __RadioButton, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ResetPasswordDialogProps as __Props } from './ResetPasswordDialog'

/** The render plan of `src/core/admin/ResetPasswordDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/ResetPasswordDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 68). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 116). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 40). */
  abstract copy(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnClose` (line 9). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnClose` (line 77). */
  abstract floating_window_close2(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 30). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 94). */
  abstract radio_button_checked_changed(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `RadioButton.OnCheckedChanged` (line 98). */
  abstract radio_button_checked_changed2(sender: __RadioButton, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 117). */
  abstract submit(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
