// Generated by @kubuno/views-compiler from src/core/admin/UsersPanel.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, Callout as __Callout, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/UsersPanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/UsersPanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 25). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 42). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 62). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 68). */
  abstract button_click4(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Callout.OnAction` (line 10). */
  abstract callout_action(sender: __Callout, e: __EventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 46). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 22). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
