// Generated by @kubuno/views-compiler from src/core/admin/alerts/AlertDetail.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AlertDetailProps as __Props } from './AlertDetail'

/** The render plan of `src/core/admin/alerts/AlertDetail.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/alerts/AlertDetail.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 7). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 48). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 55). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 62). */
  abstract button_click4(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 69). */
  abstract button_click5(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 102). */
  abstract send(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
