// Generated by @kubuno/views-compiler from src/core/admin/alerts/AlertsSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, KeyEventArgs as __KeyEventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AdminSectionProps as __Props } from './AlertsSection'

/** The render plan of `src/core/admin/alerts/AlertsSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/alerts/AlertsSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 28). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 63). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 71). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 80). */
  abstract button_click4(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 62). */
  abstract doSaveView(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 40). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 48). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `TextField.OnKeyDown` (line 57). */
  abstract text_field_key_down(sender: __TextField, e: __KeyEventArgs): void | Promise<void>
}
