// Generated by @kubuno/views-compiler from src/core/admin/ldap/LdapSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, EmptyState as __EmptyState, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/ldap/LdapSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/ldap/LdapSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 27). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `EmptyState.OnAction` (line 22). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
