// Generated by @kubuno/views-compiler from src/core/admin/ldap/LdapDirectoryForm.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { LdapDirectoryFormProps as __Props } from './LdapDirectoryForm'

/** The render plan of `src/core/admin/ldap/LdapDirectoryForm.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/ldap/LdapDirectoryForm.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 8). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 9). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 47). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 99). */
  abstract button_click4(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 103). */
  abstract button_click5(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
