// Generated by @kubuno/views-compiler from src/core/settings/sections/my-data/ServicePicker.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, CheckBox as __CheckBox, MouseEventArgs as __MouseEventArgs, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ServicePickerProps as __Props } from './ServicePicker'

/** The render plan of `src/core/settings/sections/my-data/ServicePicker.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/my-data/ServicePicker.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 9). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 10). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `CheckBox.OnCheckedChanged` (line 19). */
  abstract check_box_checked_changed(sender: __CheckBox, e: __ValueChangedEventArgs): void | Promise<void>
}
