// Generated by @kubuno/views-compiler from src/core/settings/sections/SecurityTab.kbview — do not edit (rebuilt on every change; never committed).
import type { EventArgs as __EventArgs, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/settings/sections/SecurityTab.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/settings/sections/SecurityTab.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Panel.OnSubmit` (line 5). */
  abstract panel_submit(sender: __Panel, e: __EventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 11). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
