-- ── Public holidays and special days ─────────────────────────────────────────
--
-- What day is off, where. A calendar module that cannot answer that shows a
-- Tuesday in Casablanca exactly like a Tuesday in Oslo, and a scheduling
-- assistant proposes a meeting on the 4th of July. The answer is *not* module
-- data: an agenda displays it, a task board excludes it from a deadline, a
-- workflow delays a run because of it, a payroll counts it. It is a description
-- of where the organisation lives — the same nature as accounts, groups and
-- organisational units — so it belongs to the core, like `core.buildings`.
--
-- ## Rules, not a list of dates
--
-- A calendar holds **rules** — "the 14th of July", "Easter plus one", "the last
-- Monday of May" — and not the dates they produce. Three reasons, all decisive:
--
--   1. a list of dates has an end. The day a user browses the year past it, the
--      instance answers "no holidays" — which is indistinguishable from "no
--      holidays are declared here" and is the worse of the two failures;
--   2. a rule is what an administrator can read and correct. "1 May, every
--      year" is a sentence; thirty-six rows carrying the same 1 May are not,
--      and editing them means editing all thirty-six;
--   3. a rule is stable under re-seeding. Shipping a new dataset re-matches on
--      `(calendar, key)` and leaves an edited rule alone; a date list would have
--      to be diffed year by year to find out whether anything really changed.
--
-- The one thing no Gregorian rule describes is the Islamic, Hebrew, Chinese and
-- astronomical feasts, whose date comes from another calendar entirely. Those
-- keep an explicit date list (`kind = 'dates'`), and the honest consequence is
-- recorded rather than hidden: `coverage_from`/`coverage_to` state the window
-- the shipped dataset computed, and the expander answers nothing outside it
-- instead of inventing a date.
--
-- ## Three levels of truth, and who may write each
--
--   * the **shipped dataset** (`is_builtin`) — some 250 countries and their
--     subdivisions, regenerated by `_tools/gen_holidays.py`;
--   * the **instance referential** — the same rows, which an administrator may
--     correct, disable, or extend with days of their own (a company day, a
--     local patron saint). An edit raises `is_overridden`, which is what keeps
--     the next dataset upgrade from overwriting it;
--   * the **organisational unit overlay** (`core.holiday_unit_prefs`) — a unit
--     that does not observe a day the instance declares, or that observes one
--     more. A subsidiary abroad is the case this exists for.
--
-- Nothing here grants or denies anything: a holiday is information. It is
-- readable by every signed-in account (`core.holidays.read` gates the *console*,
-- not the feed), and writable only under `core.holidays.manage`.

-- ── Calendars ────────────────────────────────────────────────────────────────
--
-- One row per country, plus one per subdivision that differs from it. A
-- subdivision **inherits**: its rows carry only what the country list does not
-- already say (Alsace-Moselle adds Good Friday and Saint Stephen's Day to the
-- eleven French ones), and `core.holiday_exclusions` names the rare national day
-- a region does not observe. Storing the full list per subdivision would mean
-- six hundred copies of Christmas, each drifting from the others the first time
-- somebody corrected one.
CREATE TABLE core.holiday_calendars (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    -- The stable identifier, and what a setting, a module request and a
    -- re-seed all match on: 'FR', 'FR-6AE', or a slug for a calendar an
    -- administrator created. Never shown as such — `name`/`names` are.
    --
    -- Upper case by construction rather than by convention: it is compared
    -- against a hand-typed setting ("fr-6ae"), and a case-insensitive unique
    -- index would then need a matching expression in every upsert. One
    -- normalisation at the door is cheaper than that, everywhere.
    code          VARCHAR(64) NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9._-]{1,64}$'),
    -- ISO 3166-1 alpha-2. NULL for a purely local calendar ("Jours de
    -- fermeture") that describes the organisation rather than a territory.
    country_code  CHAR(2) CHECK (country_code ~ '^[A-Z]{2}$'),
    -- ISO 3166-2 code, without the country prefix ('6AE', 'TX', 'BY').
    subdivision   VARCHAR(16),
    -- The country calendar a subdivision completes. NULL for a country or a
    -- standalone calendar.
    parent_id     UUID REFERENCES core.holiday_calendars(id) ON DELETE CASCADE,
    name          VARCHAR(160) NOT NULL CHECK (BTRIM(name) <> ''),
    -- locale → name, for the thirteen languages the product ships. The reader's
    -- language wins, English answers for the rest, `name` is the last word.
    names         JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_builtin    BOOLEAN NOT NULL DEFAULT FALSE,
    -- Renamed here. Same contract as on a day: the seeder reads it and leaves
    -- the row's wording alone.
    is_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    -- Whether this calendar may be *offered*. Disabling a country does not
    -- delete it: the referential stays complete, and re-enabling it brings back
    -- the administrator's edits rather than a fresh copy.
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    -- The year window the shipped date lists cover. NULL on a calendar with no
    -- date-list rule: it answers for every year.
    coverage_from INT,
    coverage_to   INT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by    UUID REFERENCES core.users(id) ON DELETE SET NULL,
    -- A subdivision without its country would answer with two days a year and
    -- look like a broken country.
    CONSTRAINT holiday_calendars_subdivision_has_parent
        CHECK (subdivision IS NULL OR parent_id IS NOT NULL)
);

CREATE INDEX idx_core_holiday_calendars_country ON core.holiday_calendars (country_code);
CREATE INDEX idx_core_holiday_calendars_parent ON core.holiday_calendars (parent_id);

CREATE TRIGGER holiday_calendars_updated_at
    BEFORE UPDATE ON core.holiday_calendars
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ── The days themselves ──────────────────────────────────────────────────────
--
-- `kind` + `rule` is a small closed grammar, and it is closed on purpose: every
-- kind below is expanded by `crate::holidays::rules`, and a kind the expander
-- does not know would be a row that stores a promise the product never keeps.
--
--   fixed        {"month": 7, "day": 14}
--   easter       {"offset": -2, "basis": "gregorian"|"julian"}   (Orthodox = julian)
--   nth_weekday  {"month": 5, "weekday": 1, "nth": -1}           (ISO weekday, -1 = last)
--   dates        {"dates": ["2026-03-20", …]}                    (non-Gregorian feasts)
CREATE TABLE core.holidays (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    calendar_id  UUID NOT NULL REFERENCES core.holiday_calendars(id) ON DELETE CASCADE,
    -- Stable within its calendar. This is what a re-seed matches on, so it is
    -- derived from the English name and never from a row id.
    key          VARCHAR(80) NOT NULL CHECK (key ~ '^[a-z0-9-]{1,80}$'),
    name         VARCHAR(200) NOT NULL CHECK (BTRIM(name) <> ''),
    names        JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Closed vocabulary: a module filters on it (an agenda shows `public`, a
    -- payroll cares about `bank`), and free text would make that filter a
    -- guess. `observance` here is the anthropological sense — a day that is
    -- marked but not off — not the weekend shift, which is the column below.
    category     VARCHAR(20) NOT NULL DEFAULT 'public'
                     CHECK (category IN ('public','bank','government','school','optional',
                                         'half_day','armed_forces','workday','observance')),
    kind         VARCHAR(16) NOT NULL
                     CHECK (kind IN ('fixed','easter','nth_weekday','dates')),
    rule         JSONB NOT NULL,
    -- What happens when the day lands on a weekend. Recorded per day rather
    -- than per country because it *is* per day: in the United States, Christmas
    -- moves to the nearest weekday and Columbus Day does not move at all.
    observance   VARCHAR(24) NOT NULL DEFAULT 'none'
                     CHECK (observance IN ('none','next_workday','nearest_workday',
                                           'sunday_to_monday','saturday_to_monday',
                                           'saturday_to_friday')),
    -- The years the day exists at all — a holiday created in 2021, or abolished
    -- in 2019. NULL on both sides means "always", which is the common case.
    from_year    INT,
    to_year      INT,
    -- Overrides the calendar colour in the modules that render it. NULL is the
    -- normal answer: a per-day colour is for the one day an organisation wants
    -- to single out.
    color        VARCHAR(9) CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{3,8}$'),
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    is_builtin   BOOLEAN NOT NULL DEFAULT FALSE,
    -- Raised the first time an administrator edits a shipped row. The seeder
    -- reads it and skips the row: an upgrade must never silently undo a
    -- correction somebody made on purpose.
    is_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    -- Raised when a shipped row disappears from a newer dataset but was edited
    -- here. Deleting it would throw away the edit; keeping it silently would
    -- keep announcing a day the source no longer knows. The console shows it as
    -- what it is, and the administrator decides.
    is_orphan    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by   UUID REFERENCES core.users(id) ON DELETE SET NULL,
    CONSTRAINT holidays_year_window CHECK (from_year IS NULL OR to_year IS NULL OR to_year >= from_year)
);

CREATE UNIQUE INDEX idx_core_holidays_key ON core.holidays (calendar_id, key);
CREATE INDEX idx_core_holidays_calendar ON core.holidays (calendar_id) WHERE enabled;

CREATE TRIGGER holidays_updated_at
    BEFORE UPDATE ON core.holidays
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ── What a subdivision does *not* observe ────────────────────────────────────
--
-- Rare, and real: Reformation Day is a national German holiday that half the
-- Länder do not take, and Holi is not observed in Maharashtra. Without this
-- table a subdivision could only ever add days, and the only way to model a
-- removal would be to copy the whole national list into every region — the
-- duplication this schema exists to avoid.
CREATE TABLE core.holiday_exclusions (
    calendar_id UUID NOT NULL REFERENCES core.holiday_calendars(id) ON DELETE CASCADE,
    -- The `key` of the parent's holiday, not its id: the exclusion must survive
    -- a re-seed that recreates the parent row.
    key         VARCHAR(80) NOT NULL,
    PRIMARY KEY (calendar_id, key)
);

-- ── The organisational-unit overlay ──────────────────────────────────────────
--
-- A unit that does not observe what the instance declares, or that observes one
-- more day. Exactly one of the two targets is set: a whole calendar (a
-- subsidiary follows Morocco rather than France) or a single day.
--
-- An overlay row, never a copy. The unit stores its *difference* from what it
-- inherits, so correcting a rule at instance level reaches every unit that had
-- not overridden it — the same invariant as `core.setting_values`, and for the
-- same reason: a materialised inherited value is a link that breaks silently.
CREATE TABLE core.holiday_unit_prefs (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_unit_id UUID NOT NULL REFERENCES core.org_units(id) ON DELETE CASCADE,
    calendar_id UUID REFERENCES core.holiday_calendars(id) ON DELETE CASCADE,
    holiday_id  UUID REFERENCES core.holidays(id) ON DELETE CASCADE,
    enabled     BOOLEAN NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by  UUID REFERENCES core.users(id) ON DELETE SET NULL,
    CONSTRAINT holiday_unit_prefs_one_target
        CHECK ((calendar_id IS NULL) <> (holiday_id IS NULL))
);

CREATE UNIQUE INDEX idx_core_holiday_unit_prefs_calendar
    ON core.holiday_unit_prefs (org_unit_id, calendar_id) WHERE calendar_id IS NOT NULL;
CREATE UNIQUE INDEX idx_core_holiday_unit_prefs_holiday
    ON core.holiday_unit_prefs (org_unit_id, holiday_id) WHERE holiday_id IS NOT NULL;

CREATE TRIGGER holiday_unit_prefs_updated_at
    BEFORE UPDATE ON core.holiday_unit_prefs
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ── Which calendar applies to whom ───────────────────────────────────────────
--
-- Through the scoped chain of migration 000060, so the answer is:
--
--   account ?? group ?? closest organisational unit ?? … ?? instance ?? factory
--
-- A list rather than one code, because the true answer is sometimes plural: a
-- cross-border team follows France *and* Belgium, and a consultant on a foreign
-- assignment wants their home country next to the local one. Empty is not
-- "none": it means "nobody said", and `crate::holidays::resolve` then deduces
-- the country from the time zone that already applies to the reader (migration
-- 000080) rather than showing an empty year to somebody who never had an
-- opinion about the setting.
INSERT INTO core.settings (key, value, default_value, category, label, description, is_public, scope, value_type) VALUES
    ('intl.holiday_calendars', '""', '""', 'intl',
     'Calendriers de jours fériés',
     'Les territoires dont les jours fériés s''affichent, séparés par des virgules (« FR », « FR-6AE,BE »). Laissé vide, le pays est déduit du fuseau horaire qui s''applique à la personne.',
     TRUE, 'overridable', 'string')
ON CONFLICT (key) DO NOTHING;

-- Whether the shipped referential is offered at all. An instance that curates
-- its own list of days turns this off and keeps only what it declared itself;
-- the shipped rows stay in place, so turning it back on costs nothing.
INSERT INTO core.settings (key, value, default_value, category, label, description, is_public, scope, value_type) VALUES
    ('intl.holidays_enabled', 'true', 'true', 'intl',
     'Jours fériés officiels',
     'Diffuser le référentiel mondial livré avec Kubuno. Désactivé, seules les journées créées ici sont proposées aux modules.',
     TRUE, 'global', 'bool')
ON CONFLICT (key) DO NOTHING;

-- The dataset version currently loaded. Written by the seeder, read by it on
-- the next boot: seeding is skipped entirely when it matches, which is what
-- keeps a multi-megabyte JSON out of every startup.
INSERT INTO core.settings (key, value, default_value, category, label, description, is_public, scope, value_type) VALUES
    ('intl.holidays_dataset', '""', '""', 'intl',
     'Version du référentiel de jours fériés',
     'Version du jeu de données livré actuellement chargée en base. Renseignée automatiquement au démarrage.',
     FALSE, 'global', 'string')
ON CONFLICT (key) DO NOTHING;

-- ── Privileges ───────────────────────────────────────────────────────────────
--
-- Reading gates the *console section*, not the feed: every signed-in account
-- reads `/api/v1/holidays`, because a holiday is public information and a
-- calendar that shows it to administrators only would be a bug, not a policy.
--
-- OU-scopable on purpose, and this is the one place it matters: delegating "may
-- adjust the days of the Casablanca unit" to somebody there is exactly the
-- delegation this overlay was built for, and it must not carry the power to
-- rewrite the instance referential.
INSERT INTO core.privileges (key, namespace, domain, verb, label, description, is_ou_scopable) VALUES
    ('core.holidays.read',   'core', 'holidays', 'read',   'Consulter les jours fériés',
     'Ouvrir le référentiel des jours fériés et journées spéciales, et voir ce qui s''applique à chaque unité.', TRUE),
    ('core.holidays.manage', 'core', 'holidays', 'manage', 'Gérer les jours fériés',
     'Créer, modifier, désactiver des journées et des calendriers de territoires, et ajuster ce qu''une unité observe.', TRUE)
ON CONFLICT (key) DO NOTHING;
