// Generated by @kubuno/views-compiler from src/core/admin/sections/resources/ResourceDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { CheckBox as __CheckBox, EventArgs as __EventArgs, FloatingWindow as __FloatingWindow, MouseEventArgs as __MouseEventArgs, NumericField as __NumericField, Panel as __Panel, TextField as __TextField, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { ResourceDialogProps as __Props } from './ResourceDialog'

/** The render plan of `src/core/admin/sections/resources/ResourceDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/resources/ResourceDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `CheckBox.OnCheckedChanged` (line 79). */
  abstract check_box_checked_changed(sender: __CheckBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `CheckBox.OnCheckedChanged` (line 92). */
  abstract check_box_checked_changed2(sender: __CheckBox, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnClose` (line 12). */
  abstract floating_window_close(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `FloatingWindow.OnConfirm` (line 11). */
  abstract floating_window_confirm(sender: __FloatingWindow, e: __EventArgs): void | Promise<void>
  /** Handles `NumericField.OnValueChanged` (line 73). */
  abstract numeric_field_value_changed(sender: __NumericField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseDown` (line 2). */
  abstract panel_mouse_down(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 52). */
  abstract text_field_text_changed(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `TextField.OnTextChanged` (line 68). */
  abstract text_field_text_changed2(sender: __TextField, e: __ValueChangedEventArgs): void | Promise<void>
}
