// Generated by @kubuno/views-compiler from src/core/admin/theme/groups/data/StepperDemo.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/theme/groups/data/StepperDemo.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/theme/groups/data/StepperDemo.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 6). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 7). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 8). */
  abstract button_click3(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
