// Generated by @kubuno/views-compiler from src/core/shell/menus/WaffleMenu.kbcontrol — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, ElementHandle as __ElementHandle, EventArgs as __EventArgs, IconButton as __IconButton, MouseEventArgs as __MouseEventArgs, ScrollArea as __ScrollArea, UserControl as __UserControl, ValueChangedEventArgs as __ValueChangedEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { WaffleMenuProps as __Props } from './WaffleMenu'

/** The render plan of `src/core/shell/menus/WaffleMenu.kbcontrol`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/shell/menus/WaffleMenu.kbcontrol`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** `<ScrollArea x:Name="body">` (line 9) */
  readonly body: __ScrollArea
  /** `<AppTileGrid x:Name="grid">` (line 11) */
  readonly grid: __ElementHandle
  /** `<IconButton x:Name="edit_button">` (line 18) */
  readonly edit_button: __IconButton
  /** `<Button x:Name="cancel_button">` (line 22) */
  readonly cancel_button: __Button
  /** `<Button x:Name="ok_button">` (line 23) */
  readonly ok_button: __Button
  /** `<MenuLink x:Name="marketplace">` (line 30) */
  readonly marketplace: __ElementHandle
  /** Handles `Button.OnClick` (line 22). */
  abstract cancel_button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `IconButton.OnClick` (line 18). */
  abstract edit_button_click(sender: __IconButton, e: __MouseEventArgs): void | Promise<void>
  /** Handles `AppTileGrid.OnFavoritesEdited` (line 13). */
  abstract grid_favorites_edited(sender: __ElementHandle, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `AppTileGrid.OnTileInvoked` (line 13). */
  abstract grid_tile_invoked(sender: __ElementHandle, e: __ValueChangedEventArgs): void | Promise<void>
  /** Handles `MenuLink.OnClick` (line 31). */
  abstract marketplace_click(sender: __ElementHandle, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 23). */
  abstract ok_button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `UserControl.OnLoad` (line 8). */
  abstract waffle_menu_load(sender: __UserControl, e: __EventArgs): void | Promise<void>
}
