import { type ReactNode } from 'react';
import { type ConfirmOptions } from '@ui/ConfirmDialog';
import { type MenuItem } from './MenuBar';
import { type WorkspaceMenuActions, type WsMenu } from './WorkspaceMenuBar';
import { type WorkspaceTheme } from './theme';
export type { MenuItem, WorkspaceTheme };
export declare function WorkspaceShell({ onBack, title, titleIcon, titleSlot, onTitleChange, onTitleCommit, titlePlaceholder, saveStatus, titleActions, onDelete, deleteConfirm, deleteTitle, subtitle, docInfo, topbarActions, search, showSearch, menuActions, extraMenus, menus, menuBar, optionsBar, toolRail, toolRailWidth, bottomBar, statusBar, theme, chromeless, topbarHeight, optionsBarHeight, statusHeight, children, }: {
    onBack?: () => void;
    title?: ReactNode;
    titleIcon?: ReactNode;
    titleSlot?: ReactNode;
    onTitleChange?: (v: string) => void;
    onTitleCommit?: () => void;
    titlePlaceholder?: string;
    saveStatus?: ReactNode;
    titleActions?: ReactNode;
    onDelete?: () => void;
    deleteConfirm?: ConfirmOptions;
    deleteTitle?: string;
    menuActions?: WorkspaceMenuActions;
    extraMenus?: WsMenu[];
    subtitle?: ReactNode;
    docInfo?: ReactNode;
    topbarActions?: ReactNode;
    search?: ReactNode;
    showSearch?: boolean;
    menus?: {
        label: string;
        items: MenuItem[];
    }[];
    menuBar?: ReactNode;
    optionsBar?: ReactNode;
    toolRail?: ReactNode;
    toolRailWidth?: number;
    bottomBar?: ReactNode;
    statusBar?: ReactNode;
    theme?: WorkspaceTheme;
    chromeless?: boolean;
    topbarHeight?: number;
    optionsBarHeight?: number;
    statusHeight?: number;
    children: ReactNode;
}): import("react").JSX.Element;
