// Generated by @kubuno/views-compiler from src/core/pages/LabelsPage.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, KeyEventArgs as __KeyEventArgs, MouseEventArgs as __MouseEventArgs, Panel as __Panel, TextField as __TextField, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/pages/LabelsPage.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/pages/LabelsPage.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 26). */
  abstract createLabel(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 77). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `TextField.OnKeyDown` (line 21). */
  abstract text_field_key_down(sender: __TextField, e: __KeyEventArgs): void | Promise<void>
}
