// Generated by @kubuno/views-compiler from src/core/admin/rules/ConditionTester.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { Props as __Props } from './ConditionTester'

/** The render plan of `src/core/admin/rules/ConditionTester.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/rules/ConditionTester.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 12). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 19). */
  abstract clear(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 11). */
  abstract run(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
