/**
 * Data elements: `DataTable` and its `Column` items.
 * Names, kinds, defaults and documentation follow the desktop registry (VIEWS-SPEC §2, §9).
 */
import type { ComponentProps } from 'react'
import type { DataTable, DataTableColumn } from '../DataTable'
import type { ElementMeta } from './types.ts'

export const DataTableMeta = {
  name: 'DataTable',
  doc: 'A data table with sortable columns and pages. Declare the columns as Column children.',
  docFr: 'Tableau de données avec colonnes triables et pagination. Déclarez les colonnes comme éléments Column enfants.',
  family: 'data',
  baseChain: ['DataTable', 'Control', 'Component'],
  children: 'List',
  allowedChildren: ['Column'],
  defaultEvent: 'OnSelectionChanged',
  properties: [
    { name: 'ItemsSource', kind: 'String', default: '', category: 'Data',
      doc: 'Binding to the list of rows to show. Each column shows the field named by its Binding.',
      docFr: 'Liaison vers la liste des lignes à afficher. Chaque colonne affiche le champ nommé par sa Binding.',
      to: { prop: 'rows', convert: 'items-source' } },
    { name: 'SelectedIndex', kind: 'F32', default: '-1', category: 'Data',
      doc: 'Index of the selected row in ItemsSource (whatever the sort), starting at 0. -1 means none.',
      docFr: 'Index de la ligne sélectionnée, à partir de 0. -1 signifie aucune.',
      to: { prop: 'selectedIndex', change: 'OnSelectionChanged' } },
    { name: 'Density', kind: { Enum: ['Compact', 'Normal', 'Comfortable'] }, default: 'Normal', category: 'Appearance', bindable: true,
      doc: 'Height of the rows.', docFr: 'Hauteur des lignes.',
      to: { prop: 'density', values: { Compact: 'compact', Normal: 'normal', Comfortable: 'comfortable' } } },
    { name: 'EmptyTitle', kind: 'String', default: '', category: 'Appearance', bindable: true,
      doc: 'Title shown when there is no row. Empty uses the default text.', docFr: "Titre affiché quand il n'y a aucune ligne. Vide utilise le texte par défaut.",
      to: { prop: 'emptyTitle' } },
    { name: 'EmptyText', kind: 'String', default: '', category: 'Appearance', bindable: true,
      doc: 'Description shown when there is no row. Empty uses the default text.', docFr: "Description affichée quand il n'y a aucune ligne. Vide utilise le texte par défaut.",
      to: { prop: 'emptyText' } },
    { name: 'PageSize', kind: 'F32', default: '0', category: 'Paging', bindable: true,
      doc: 'Number of rows per page. 0 shows every row without a pager.',
      docFr: 'Nombre de lignes par page. 0 affiche toutes les lignes sans pagination.',
      to: { prop: 'pageSize' } },
    { name: 'PageIndex', kind: 'F32', default: '0', category: 'Paging', bindable: true,
      doc: 'Page shown, starting at 0. A two-way binding follows the pager.',
      docFr: 'Page affichée, à partir de 0. Une liaison bidirectionnelle suit la pagination.',
      to: { prop: 'page', change: 'OnPageChanged' } },
    { name: 'TotalRows', kind: 'F32', default: '-1', category: 'Paging', bindable: true,
      doc: 'Total number of rows when you fetch one page at a time: ItemsSource then holds only the page shown. -1 pages the rows itself.',
      docFr: "Nombre total de lignes quand vous chargez une page à la fois : ItemsSource ne contient alors que la page affichée. -1 pagine les lignes lui-même.",
      to: { prop: 'totalRows' } },
    { name: 'Loading', kind: 'Bool', default: 'false', category: 'Behavior', bindable: true,
      doc: 'Shows placeholder rows while the data is loading.', docFr: "Affiche des lignes d'attente pendant le chargement des données.",
      to: { prop: 'loading' } },
    { name: 'ErrorText', kind: 'String', default: '', category: 'Behavior', bindable: true,
      doc: 'When not empty, the table shows an error with this description instead of its rows.',
      docFr: 'Si non vide, le tableau affiche une erreur avec cette description au lieu de ses lignes.',
      to: { prop: 'error' } },
    { name: 'SortColumn', kind: 'String', default: '', category: 'Behavior', bindable: true,
      doc: 'Field of the column the rows are sorted by.', docFr: 'Champ de la colonne selon laquelle les lignes sont triées.',
      to: { prop: 'sort', field: 'columnId' } },
    { name: 'SortOrder', kind: { Enum: ['None', 'Ascending', 'Descending'] }, default: 'None', category: 'Behavior', bindable: true,
      doc: 'Direction of the sort.', docFr: 'Sens du tri.',
      to: { prop: 'sort', field: 'direction', values: { None: null, Ascending: 'asc', Descending: 'desc' } } },
    { name: 'Title', kind: 'String', default: '', category: 'Appearance', localizable: true, webOnly: true,
      doc: 'Web only: title shown above the table, in its toolbar.', docFr: "Web uniquement : titre affiché au-dessus du tableau, dans sa barre d'outils.",
      to: { prop: 'title' } },
    { name: 'Selectable', kind: 'Bool', default: 'false', category: 'Behavior', webOnly: true,
      doc: 'Web only: adds a check box per row for selecting several rows.',
      docFr: 'Web uniquement : ajoute une case à cocher par ligne pour sélectionner plusieurs lignes.',
      to: { prop: 'selectable' } },
  ],
  events: [
    { name: 'OnSelectionChanged', category: 'Behavior', args: 'ValueChangedEventArgs',
      doc: 'Occurs when the selected row changes. The value is its index in ItemsSource (-1: none).',
      docFr: 'Se produit quand la ligne sélectionnée change.',
      from: { prop: 'onSelectedIndexChange', args: 'value' } },
    { name: 'OnRowActivated', category: 'Action', args: 'ItemActivateEventArgs',
      doc: 'Occurs when a row is double-clicked, or Enter is pressed on it: e.item is the row, e.index its index in ItemsSource.',
      docFr: 'Se produit quand une ligne est double-cliquée.',
      from: { prop: 'onRowActivate', args: 'row' } },
    { name: 'OnSortChanged', category: 'Behavior', args: 'ValueChangedEventArgs',
      doc: 'Occurs when a column header is clicked to sort the table.',
      docFr: 'Se produit quand un en-tête de colonne est cliqué pour trier le tableau.',
      from: { prop: 'onSortChange', args: 'sort' } },
    { name: 'OnPageChanged', category: 'Behavior', args: 'ValueChangedEventArgs',
      doc: 'Occurs when the user moves to another page. The value is the new page, starting at 0.',
      docFr: "Se produit quand l'utilisateur passe à une autre page. La valeur est la nouvelle page, à partir de 0.",
      from: { prop: 'onPageChange', args: 'value' } },
  ],
  designDefaults: { size: [480, 240] },
  web: { module: '@ui', export: 'DataTable', domRoot: 'wrapper', childrenToProp: { prop: 'columns', item: 'Column', content: 'none', key: 'id' } },
} as const satisfies ElementMeta<ComponentProps<typeof DataTable>>

export const ColumnMeta = {
  name: 'Column',
  doc: 'A column of a ListView or DataTable.',
  docFr: "Colonne d'une ListView ou d'une DataTable.",
  family: 'data',
  baseChain: ['Column', 'Component'],
  children: 'None',
  defaultEvent: null,
  properties: [
    { name: 'Header', kind: 'String', default: '', category: 'Appearance',
      doc: 'Text of the column header.', docFr: "Texte de l'en-tête de colonne.", to: { prop: 'header' } },
    { name: 'Binding', kind: 'String', default: '', category: 'Data',
      doc: 'Field of each row shown in this column, for example {Binding Name}.',
      docFr: 'Champ de chaque ligne affiché dans cette colonne, par exemple {Binding Name}.',
      to: { prop: 'cell', convert: 'binding-cell' } },
    { name: 'Width', kind: 'F32', default: '160', category: 'Layout',
      doc: 'Width of the column, in pixels.', docFr: 'Largeur de la colonne, en pixels.', to: { prop: 'width' } },
    // Read by the `binding-cell` renderer.
    { name: 'FormatString', kind: 'String', default: '', category: 'Appearance',
      doc: 'Format of the values shown in this column, for example N2 for a number with two decimals or d for a short date. Empty shows the values as they are.',
      docFr: 'Format des valeurs affichées dans cette colonne, par exemple N2 pour un nombre à deux décimales ou d pour une date courte. Vide affiche les valeurs telles quelles.',
      to: { runtime: 'item-state' } },
    { name: 'Culture', kind: 'String', default: '', category: 'Appearance',
      doc: "Culture used to format and read the values of this column, for example fr-FR. Empty uses the table's culture.",
      docFr: 'Culture utilisée pour mettre en forme et relire les valeurs de cette colonne, par exemple fr-FR. Vide utilise la culture du tableau.',
      to: { runtime: 'item-state' } },
    { name: 'NullValue', kind: 'String', default: '', category: 'Appearance',
      doc: 'Text shown for an empty value. Typing it writes an empty value back.',
      docFr: 'Texte affiché pour une valeur vide. Le saisir réécrit une valeur vide.',
      to: { runtime: 'item-state' } },
    { name: 'Alignment', kind: { Enum: ['Left', 'Center', 'Right'] }, default: 'Left', category: 'Appearance',
      doc: 'Horizontal alignment of the values in this column.', docFr: 'Alignement horizontal des valeurs de cette colonne.',
      to: { prop: 'align', values: { Left: 'left', Center: 'center', Right: 'right' } } },
  ],
  events: [],
  web: { module: null, export: null, domRoot: 'none', itemOf: ['DataTable', 'ListView'] },
} as const satisfies ElementMeta<DataTableColumn<unknown>>
