// Generated by @kubuno/views-compiler from src/core/admin/sections/subscription/Field.kbview — do not edit (rebuilt on every change; never committed).
import type { View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { FieldProps as __Props } from './Field'

/** The render plan of `src/core/admin/sections/subscription/Field.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/sections/subscription/Field.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare class ViewBase extends __View<__Props> {
}
