// Generated by @kubuno/views-compiler from src/core/admin/database/SchemaPrefixCard.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/admin/database/SchemaPrefixCard.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/database/SchemaPrefixCard.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Button.OnClick` (line 33). */
  abstract onSave(sender: __Button, e: __MouseEventArgs): void | Promise<void>
}
