// Generated by @kubuno/views-compiler from src/core/shell/RightPanel.kbview — do not edit (rebuilt on every change; never committed).
import type { MouseEventArgs as __MouseEventArgs, Panel as __Panel, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'

/** The render plan of `src/core/shell/RightPanel.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/shell/RightPanel.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<{}> {
  /** Handles `Panel.OnClick` (line 7). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
}
