import type React from 'react';
import type { PendingItem } from '@kubuno/sdk';
import type { Folder, FileItem } from '../api';
export declare function useExplorerKeyboard({ orderedIds, selectedIds, setSelectedIds, cursorId, setCursorId, lastSelectedIdxRef, itemTypeMap, canDelete, hasPlayingInSelection, scheduleDelete, sortedFolders, filteredFiles, navigateTo, openFile, containerRef, }: {
    orderedIds: string[];
    selectedIds: Set<string>;
    setSelectedIds: React.Dispatch<React.SetStateAction<Set<string>>>;
    cursorId: string | null;
    setCursorId: (id: string | null) => void;
    lastSelectedIdxRef: React.MutableRefObject<number>;
    itemTypeMap: Map<string, 'file' | 'folder'>;
    canDelete: boolean;
    hasPlayingInSelection: boolean;
    scheduleDelete: (items: PendingItem[], forcePermanent?: boolean) => void;
    sortedFolders: Folder[];
    filteredFiles: FileItem[];
    navigateTo: (folder: Folder) => void;
    openFile: (file: FileItem) => void;
    containerRef: React.RefObject<HTMLDivElement | null>;
}): void;
