//! Kubuno's database foundation — one binary, three engines, chosen at run time.
//!
//! The administrator picks the engine (PostgreSQL, MySQL/MariaDB, or SQLite) in
//! configuration, at install time or later; the same binary connects to
//! whichever is named. This crate is what makes the rest of the code
//! independent of that choice:
//!
//! * [`DbPool`] / [`DbTx`] — an enum over the three concrete sqlx pools and
//!   transactions, replacing `PgPool` and `Transaction<'_, Postgres>` in
//!   signatures;
//! * [`DbValue`] and [`params!`] — engine-agnostic bind parameters;
//! * [`dialect`] — the fragments the three engines spell differently, as
//!   methods on [`Backend`];
//! * [`returning`] — how to get a row back on MySQL, which has no `RETURNING`;
//! * [`pool`] — connecting, the per-engine session policy, migrations;
//! * [`events`] — `pg_notify` and its outbox fallback;
//! * [`journal`] — the portable change-journal primitive (monotonic per-domain
//!   sequence, tombstones, delta pull) that replaces the PostgreSQL
//!   sequence-and-trigger delta layer the modules share.
//!
//! # Why an enum rather than a generic `Pool<DB>`
//!
//! Writing `async fn f<DB: Database>(pool: &Pool<DB>)` forces every caller to
//! carry the bounds that let a `Uuid`, a `DateTime<Utc>` or a `serde_json::Value`
//! be bound and decoded — `for<'a> Uuid: Encode<'a, DB>`, `Uuid: Type<DB>`, and
//! a pair more per type per function. Those bounds are viral: they climb from
//! the query up through the service, the handler and `AppState`. Kubuno binds a
//! `Uuid` in thousands of places.
//!
//! The enum keeps the engine choice a run-time value and hides it behind a small
//! set of methods (`db.fetch_one_as`, `db.execute`, `db.begin`). A bound value
//! travels as a [`DbValue`] and is encoded against the concrete driver only at
//! the moment of execution.
//!
//! `sqlx::Any` was a third option and is not usable: it carries only
//! Null/Bool/…/Text/Blob, so `Uuid`, `Json` and `DateTime<Utc>` cannot cross it.
//!
//! # sqlx does not translate SQL
//!
//! The SQL text is made correct for the engine by the [`dialect`] layer before
//! it ever reaches sqlx; sqlx only carries the text and encodes/decodes the
//! parameters. [`sql::prepare`] rewrites `$1` into `?` where the engine wants it
//! and rejects text no engine could run faithfully — it is not a translator.

pub mod dialect;
pub mod events;
pub mod exec;
pub mod json;
pub mod journal;
pub mod pool;
pub mod query;
pub mod returning;
pub mod schema;
pub mod schema_admin;
pub mod search;
pub mod sql;
pub mod value;

pub use dialect::Backend;
pub use journal::{changes_since, next_seq, next_seq_on_pool, record_tombstone, touch, Change};
pub use exec::{DbPool, DbRow, DbTx, FromAnyRow, ScalarAnyRow};
pub use json::JsonVec;
pub use pool::{connect, DbSettings, MigratorSet, SetupError};
pub use query::DbQueryBuilder;
pub use schema::{SchemaPrefix, KUBUNO_SCHEMAS};
pub use schema_admin::{
    copy_schema, discover_prefixed_schemas, rename_schema_prefix, AdminError, CopyReport,
    PrefixRename, TableCopy,
};
pub use search::{normalize, Field, Query, SearchSql, Weight};
pub use sql::{lint, Lint, SqlError};
pub use value::DbValue;

/// Re-exported so a module can reach sqlx (and `sqlx::migrate!`, used by
/// [`migrations!`]) through this crate, with the feature set already agreed on.
pub use sqlx;

/// A fresh primary key, generated by the process rather than by the database.
///
/// Kubuno's tables declare `DEFAULT gen_random_uuid()`, which neither MySQL nor
/// SQLite has and which — more importantly — makes the new key unknowable
/// without `RETURNING`. **Every insert that needs its key back must generate it
/// here and bind it explicitly.**
#[inline]
pub fn new_id() -> uuid::Uuid {
    uuid::Uuid::new_v4()
}
