// Generated by @kubuno/views-compiler from src/core/admin/storage/StorageSection.kbview — do not edit (rebuilt on every change; never committed).
import type { Button as __Button, Callout as __Callout, EmptyState as __EmptyState, EventArgs as __EventArgs, MouseEventArgs as __MouseEventArgs, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AdminSectionProps as __Props } from './StorageSection'

/** The render plan of `src/core/admin/storage/StorageSection.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/admin/storage/StorageSection.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Button.OnClick` (line 173). */
  abstract button_click(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Button.OnClick` (line 174). */
  abstract button_click2(sender: __Button, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Callout.OnAction` (line 32). */
  abstract callout_action(sender: __Callout, e: __EventArgs): void | Promise<void>
  /** Handles `EmptyState.OnAction` (line 13). */
  abstract empty_state_action(sender: __EmptyState, e: __EventArgs): void | Promise<void>
}
