// Generated by @kubuno/views-compiler from src/core/shell/AppearanceDialog.kbview — do not edit (rebuilt on every change; never committed).
import type { MouseEventArgs as __MouseEventArgs, Panel as __Panel, Stack as __Stack, View as __View, ViewPlan as __ViewPlan } from '@kubuno/views'
import type { AppearanceDialogProps as __Props } from './AppearanceDialog'

/** The render plan of `src/core/shell/AppearanceDialog.kbview`. */
export declare const plan: __ViewPlan

/** The generated base of the code-behind of `src/core/shell/AppearanceDialog.kbview`: one handle per `x:Name`, one abstract method per handler. */
export declare abstract class ViewBase extends __View<__Props> {
  /** Handles `Panel.OnClick` (line 19). */
  abstract panel_click(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnClick` (line 45). */
  abstract panel_click2(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Panel.OnMouseDown` (line 15). */
  abstract panel_mouse_down(sender: __Panel, e: __MouseEventArgs): void | Promise<void>
  /** Handles `Stack.OnMouseDown` (line 8). */
  abstract stack_mouse_down(sender: __Stack, e: __MouseEventArgs): void | Promise<void>
}
